/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KokoroSpikeRouteImport } from './routes/kokoro-spike'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioProjectIdRouteImport } from './routes/studio.$projectId'
import { Route as ApiVoicesRouteImport } from './routes/api/voices'
import { Route as ApiStitchRouteImport } from './routes/api/stitch'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as ApiCapabilitiesRouteImport } from './routes/api/capabilities'
import { Route as ApiAlignRouteImport } from './routes/api/align'
import { Route as ApiVoicePreviewSlugRouteImport } from './routes/api/voice-preview.$slug'
import { Route as ApiProjectsIdRouteImport } from './routes/api/projects.$id'
import { Route as ApiAudioRunIdRouteImport } from './routes/api/audio.$runId'
import { Route as ApiAudioRunIdPeaksRouteImport } from './routes/api/audio.$runId.peaks'

const KokoroSpikeRoute = KokoroSpikeRouteImport.update({
  id: '/kokoro-spike',
  path: '/kokoro-spike',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioProjectIdRoute = StudioProjectIdRouteImport.update({
  id: '/studio/$projectId',
  path: '/studio/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoicesRoute = ApiVoicesRouteImport.update({
  id: '/api/voices',
  path: '/api/voices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStitchRoute = ApiStitchRouteImport.update({
  id: '/api/stitch',
  path: '/api/stitch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCapabilitiesRoute = ApiCapabilitiesRouteImport.update({
  id: '/api/capabilities',
  path: '/api/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlignRoute = ApiAlignRouteImport.update({
  id: '/api/align',
  path: '/api/align',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoicePreviewSlugRoute = ApiVoicePreviewSlugRouteImport.update({
  id: '/api/voice-preview/$slug',
  path: '/api/voice-preview/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdRoute = ApiProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProjectsRoute,
} as any)
const ApiAudioRunIdRoute = ApiAudioRunIdRouteImport.update({
  id: '/api/audio/$runId',
  path: '/api/audio/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioRunIdPeaksRoute = ApiAudioRunIdPeaksRouteImport.update({
  id: '/peaks',
  path: '/peaks',
  getParentRoute: () => ApiAudioRunIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kokoro-spike': typeof KokoroSpikeRoute
  '/api/align': typeof ApiAlignRoute
  '/api/capabilities': typeof ApiCapabilitiesRoute
  '/api/export': typeof ApiExportRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/stitch': typeof ApiStitchRoute
  '/api/voices': typeof ApiVoicesRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
  '/api/audio/$runId': typeof ApiAudioRunIdRouteWithChildren
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/api/voice-preview/$slug': typeof ApiVoicePreviewSlugRoute
  '/api/audio/$runId/peaks': typeof ApiAudioRunIdPeaksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kokoro-spike': typeof KokoroSpikeRoute
  '/api/align': typeof ApiAlignRoute
  '/api/capabilities': typeof ApiCapabilitiesRoute
  '/api/export': typeof ApiExportRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/stitch': typeof ApiStitchRoute
  '/api/voices': typeof ApiVoicesRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
  '/api/audio/$runId': typeof ApiAudioRunIdRouteWithChildren
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/api/voice-preview/$slug': typeof ApiVoicePreviewSlugRoute
  '/api/audio/$runId/peaks': typeof ApiAudioRunIdPeaksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kokoro-spike': typeof KokoroSpikeRoute
  '/api/align': typeof ApiAlignRoute
  '/api/capabilities': typeof ApiCapabilitiesRoute
  '/api/export': typeof ApiExportRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/stitch': typeof ApiStitchRoute
  '/api/voices': typeof ApiVoicesRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
  '/api/audio/$runId': typeof ApiAudioRunIdRouteWithChildren
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/api/voice-preview/$slug': typeof ApiVoicePreviewSlugRoute
  '/api/audio/$runId/peaks': typeof ApiAudioRunIdPeaksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kokoro-spike'
    | '/api/align'
    | '/api/capabilities'
    | '/api/export'
    | '/api/generate'
    | '/api/projects'
    | '/api/stitch'
    | '/api/voices'
    | '/studio/$projectId'
    | '/api/audio/$runId'
    | '/api/projects/$id'
    | '/api/voice-preview/$slug'
    | '/api/audio/$runId/peaks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kokoro-spike'
    | '/api/align'
    | '/api/capabilities'
    | '/api/export'
    | '/api/generate'
    | '/api/projects'
    | '/api/stitch'
    | '/api/voices'
    | '/studio/$projectId'
    | '/api/audio/$runId'
    | '/api/projects/$id'
    | '/api/voice-preview/$slug'
    | '/api/audio/$runId/peaks'
  id:
    | '__root__'
    | '/'
    | '/kokoro-spike'
    | '/api/align'
    | '/api/capabilities'
    | '/api/export'
    | '/api/generate'
    | '/api/projects'
    | '/api/stitch'
    | '/api/voices'
    | '/studio/$projectId'
    | '/api/audio/$runId'
    | '/api/projects/$id'
    | '/api/voice-preview/$slug'
    | '/api/audio/$runId/peaks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KokoroSpikeRoute: typeof KokoroSpikeRoute
  ApiAlignRoute: typeof ApiAlignRoute
  ApiCapabilitiesRoute: typeof ApiCapabilitiesRoute
  ApiExportRoute: typeof ApiExportRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiProjectsRoute: typeof ApiProjectsRouteWithChildren
  ApiStitchRoute: typeof ApiStitchRoute
  ApiVoicesRoute: typeof ApiVoicesRoute
  StudioProjectIdRoute: typeof StudioProjectIdRoute
  ApiAudioRunIdRoute: typeof ApiAudioRunIdRouteWithChildren
  ApiVoicePreviewSlugRoute: typeof ApiVoicePreviewSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kokoro-spike': {
      id: '/kokoro-spike'
      path: '/kokoro-spike'
      fullPath: '/kokoro-spike'
      preLoaderRoute: typeof KokoroSpikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$projectId': {
      id: '/studio/$projectId'
      path: '/studio/$projectId'
      fullPath: '/studio/$projectId'
      preLoaderRoute: typeof StudioProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voices': {
      id: '/api/voices'
      path: '/api/voices'
      fullPath: '/api/voices'
      preLoaderRoute: typeof ApiVoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stitch': {
      id: '/api/stitch'
      path: '/api/stitch'
      fullPath: '/api/stitch'
      preLoaderRoute: typeof ApiStitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/capabilities': {
      id: '/api/capabilities'
      path: '/api/capabilities'
      fullPath: '/api/capabilities'
      preLoaderRoute: typeof ApiCapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/align': {
      id: '/api/align'
      path: '/api/align'
      fullPath: '/api/align'
      preLoaderRoute: typeof ApiAlignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice-preview/$slug': {
      id: '/api/voice-preview/$slug'
      path: '/api/voice-preview/$slug'
      fullPath: '/api/voice-preview/$slug'
      preLoaderRoute: typeof ApiVoicePreviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id': {
      id: '/api/projects/$id'
      path: '/$id'
      fullPath: '/api/projects/$id'
      preLoaderRoute: typeof ApiProjectsIdRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/api/audio/$runId': {
      id: '/api/audio/$runId'
      path: '/api/audio/$runId'
      fullPath: '/api/audio/$runId'
      preLoaderRoute: typeof ApiAudioRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio/$runId/peaks': {
      id: '/api/audio/$runId/peaks'
      path: '/peaks'
      fullPath: '/api/audio/$runId/peaks'
      preLoaderRoute: typeof ApiAudioRunIdPeaksRouteImport
      parentRoute: typeof ApiAudioRunIdRoute
    }
  }
}

interface ApiProjectsRouteChildren {
  ApiProjectsIdRoute: typeof ApiProjectsIdRoute
}

const ApiProjectsRouteChildren: ApiProjectsRouteChildren = {
  ApiProjectsIdRoute: ApiProjectsIdRoute,
}

const ApiProjectsRouteWithChildren = ApiProjectsRoute._addFileChildren(
  ApiProjectsRouteChildren,
)

interface ApiAudioRunIdRouteChildren {
  ApiAudioRunIdPeaksRoute: typeof ApiAudioRunIdPeaksRoute
}

const ApiAudioRunIdRouteChildren: ApiAudioRunIdRouteChildren = {
  ApiAudioRunIdPeaksRoute: ApiAudioRunIdPeaksRoute,
}

const ApiAudioRunIdRouteWithChildren = ApiAudioRunIdRoute._addFileChildren(
  ApiAudioRunIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KokoroSpikeRoute: KokoroSpikeRoute,
  ApiAlignRoute: ApiAlignRoute,
  ApiCapabilitiesRoute: ApiCapabilitiesRoute,
  ApiExportRoute: ApiExportRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiProjectsRoute: ApiProjectsRouteWithChildren,
  ApiStitchRoute: ApiStitchRoute,
  ApiVoicesRoute: ApiVoicesRoute,
  StudioProjectIdRoute: StudioProjectIdRoute,
  ApiAudioRunIdRoute: ApiAudioRunIdRouteWithChildren,
  ApiVoicePreviewSlugRoute: ApiVoicePreviewSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
