/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVoicesRouteImport } from './routes/api/voices'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as ApiAudioRunIdRouteImport } from './routes/api/audio.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoicesRoute = ApiVoicesRouteImport.update({
  id: '/api/voices',
  path: '/api/voices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioRunIdRoute = ApiAudioRunIdRouteImport.update({
  id: '/api/audio/$runId',
  path: '/api/audio/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/export': typeof ApiExportRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/voices': typeof ApiVoicesRoute
  '/api/audio/$runId': typeof ApiAudioRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/export': typeof ApiExportRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/voices': typeof ApiVoicesRoute
  '/api/audio/$runId': typeof ApiAudioRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/export': typeof ApiExportRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/voices': typeof ApiVoicesRoute
  '/api/audio/$runId': typeof ApiAudioRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/export' | '/api/generate' | '/api/voices' | '/api/audio/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/api/export' | '/api/generate' | '/api/voices' | '/api/audio/$runId'
  id:
    | '__root__'
    | '/'
    | '/api/export'
    | '/api/generate'
    | '/api/voices'
    | '/api/audio/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiExportRoute: typeof ApiExportRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiVoicesRoute: typeof ApiVoicesRoute
  ApiAudioRunIdRoute: typeof ApiAudioRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voices': {
      id: '/api/voices'
      path: '/api/voices'
      fullPath: '/api/voices'
      preLoaderRoute: typeof ApiVoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio/$runId': {
      id: '/api/audio/$runId'
      path: '/api/audio/$runId'
      fullPath: '/api/audio/$runId'
      preLoaderRoute: typeof ApiAudioRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiExportRoute: ApiExportRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiVoicesRoute: ApiVoicesRoute,
  ApiAudioRunIdRoute: ApiAudioRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
