services:
  tts:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ../../voices:/app/voices
      - ./generated_audio:/app/generated_audio
    environment:
      - PYTHONUNBUFFERED=1
      - VOICES_DIR=/app/voices
